# קובץ ה-"מוח" של שרת הפרוקסי. תפקידו של שרת הפרוקסי הוא להוות נקודת גישה יחידה.
#  במקום שהמשתמש יצטרך לדעת איך להגיע לאפליקציה (שנמצאת בפורט 5000) ואיך להגיע לדף התצוגה (ה-Dashboard) הוא פונה לפורט 80 והפרוקסי מחליט בהתאם איך לנווט אותו.

server{
    listen 80; # שרת הפרוקסי יאזין על פורט 80

    location / { # הגדרה מה קורה כשמישהו נכנס לכתובת הראשית, במקרה שלנו localhost
        root /usr/share/nginx/html; # אומר לפרוקסי איפה נמאים הקבצים הסטיים שזה בעצם ה-HTML
        index index.html; # אם המשתמש לא ביקש קובץ ספציפי, תציג לו את index.html
    }

    location /api{ # הגדרה למה קורה כשמישהו פונה לכתובת שמסתיימת ב-api/
        proxy_pass http://app:5000/api; # אומרת לפרוקסי "אל תחפש קובץ להציג לו אצלך, תעביר את הבקשה ל-app"
        proxy_set_header Host $host; # שורות המעבירות לאפליקציה מידע על המשתמש בשביל שלא תחשוב שפרוקסי הוא זה שמבקש את הבקשות באמת - הוא רק מתווך
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ingredients {
        proxy_pass http://app:5000/api/ingredients;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/suggest { # העברת בקשות ה-POST עם מצרכים וסוג ארוחה לאפליקציה
        proxy_pass http://app:5000/api/suggest;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}